version: '3.8'
services:
  auth:
    container_name: auth-service
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - '4000:4000'
    command: [sh, -c, "npm run migration:run && npm run start:dev"]
    env_file:
      - .env
    networks:
      - authnet
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_ADMIN_USER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_TENANT_USER: ${POSTGRES_TENANT_USER}
      POSTGRES_TENANT_PASSWORD: ${POSTGRES_TENANT_PASSWORD}
    expose:
      - '5432'
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    env_file:
      - docker.env
    networks:
      - authnet

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - authnet

  redis:
    container_name: cache
    image: 'redis'
    expose:
      - '6379'
    ports:
      - '6379:6379'
    env_file:
      - docker.env
    networks:
      - authnet

networks:
  authnet:
    driver: bridge
